# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'storyboard' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for storyboard
  pod 'AlamofireImage'

  target 'storyboardTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'storyboardUITests' do
    # Pods for testing
  end

end
